### ISSUE TITLE
BreakDoImmediateProcessingIntoSmallerChunks

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#104]
`OPUNetTransportLayer::DoImmediateProcessing` is currently about 231 lines of code. It looks like there are 2 major groupings of messages, which could each be further broken down into 3 - 4 functions. Open to different naming schema than below.

- ProcessGameHostQueries
  -   ProcessJoinRequest
  -   ProcessHostedGameSearchQuery
  -   ProcessJoinHelpRequest
- ProcessPreGameSetupMessages
  -   ProcessSetPlayersList
  -   ProcessSetPlayersListFailed
  -   ProcessUpdateStatus
  -   ProcessHostedGameSearchReply

**Comment by DanRStevens** [comment]
The `DoImmediateProcessing` method appears to be event handling code, so perhaps an `OnX` style naming convention would be appropriate.

The root method is a little funny there, since it contains a check to see if the packet should be immediately processed at the start of the method, so it's not yet known if it's an event to process immediately. Not sure if the check should stay there (and perhaps be reflected in the naming), or if the check should be moved to the caller, and the method named `OnImmediatePacket` or something.

The other methods look like a good breakdown for the handling code.

**Comment by Brett208** [comment]
To close this issue out, there was a function name comment in the branch that I pulled in here:

> Oh, one comment I forgot to make earlier. In regards to #104, all of the listed method are event handlers methods, and so all can be named in the OnX style. It was only the root method with the integrated check that was maybe a little odd for that naming.

I think the names below would suffice?

- OnJoinRequest
- OnHostedGameSearchQuery
- OnJoinHelpRequest
- OnSetPlayersList
- OnSetPlayersListFailed
- OnUpdateStatus
- OnHostedGameSearchReply

---

It would be nice if we could validate if the function continuation in the `tlcJoinHelpRequest` case is meant or if it is a mistake and can be treated as a straight return whether it is true or false. I guess one would need to prove that `bGameStarted` could not be set to false when `tlcJoinHelpRequest` if processed or already be false when processing `tlcJoinHelpRequest`.

```C++
case tlcJoinHelpRequest:
	if (ProcessJoinHelpRequest(packet, fromAddress, tlMessage)) {
		return true;
	}
break;
```

**Comment by DanRStevens** [comment]
Well, the game has definitely not started if people are still joining. I have a feeling it was intentional.

----

The proposed method names look good.
