### ISSUE TITLE
Use nullptr where appropriate

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#13]
I'm seeing places where raw pointers are assigned to zero. I think it would be more appropriate to use nullptr in these places to be more explicit about what is happening.

I suspect nullptr wasn't available when this was initially coded.

-Brett

**Comment by DanRStevens** [comment]
Agreed. And you're right, `nullptr` wasn't in the language back then. We should use it now.

**Comment by ldicker83** [comment]
NULL was available and in most implementations was just a macro that was defined as 0 but that's still kind of a poor excuse to not at least use a named constant.

**Comment by DanRStevens** [comment]
True, though using [`NULL`](https://en.cppreference.com/w/cpp/types/NULL) requires having a proper header include for it, since it's not a compiler built in.

Not really a big deal here, though at the time I was trying to keep header includes to a minimum.

Side note: This was interesting:
[Migrating from C to C++: NULL vs nullptr](https://embeddedartistry.com/blog/2017/2/28/migrating-from-c-to-c-null-vs-nullptr).
