### ISSUE TITLE
Add a debug configuration

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#14]
Currently, there is only a release configuration in NetFixClient. I'd like to add a debug configuration. Is there anything about OP2Internal or NetFix itself that would preclude a standard debug configuration from being used?

**Comment by DanRStevens** [comment]
No, I don't believe there is a problem with adding a Debug configuration. I probably just deleted it at projection creation because I hated Debug settings back then. I was always getting confused by project settings only being applied to one of Release or Debug when I'd intended changes to apply to both. As I never really used Debug, I often tended to just get rid of it to simplify things.

Go ahead and add a Debug configuration if it helps. And if might if you're actually using the integrated debugger.

**Comment by Brett208** [comment]
Actually, I still forget to check which configuration I'm editing when messing with project files, so I find that annoying as well although since I use the integrated debugger, it is nice to get clean step-throughs that match up nicely with the source code.
