### ISSUE TITLE
Add op2ext as a submodule

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#24]
I'd like to add op2ext as a submodule and hook it to NetFixClient's solutions.

I think the long term plan is to use op2ext's logger, so it would be nice to bring in the public include header from op2ext. Also, standardizing the location of op2ext relative to NetFixClient would ease my testing a bit.

If it is agreeable, I'll volunteer to do the work.

**Comment by DanRStevens** [comment]
I was thinking about this recently, while browsing through the messy debug output code. There's a lot of it though. It left me thinking an intermediate cleanup step might make the process easier. You're welcome to go ahead though.

I'm curious about how standardizing the location will aid debugging. Do you mean once you start on this, or now currently there is a reason for it?

**Comment by DanRStevens** [comment]
I was having some additional thoughts on the logging. If we want to instrument NetFixClient to better diagnose network errors, we may need more advanced logging than is provided by op2ext. In particular, it would be useful if logged events could be sent to a central server for analysis. This would be particularly useful to diagnose NAT port mapping issues caused by a variety of router settings.

I'm not sure how this will impact logging. Maybe it will be separate from logging. Maybe we need to log to a special logger, which can then delegate to op2ext for logging to the standard log. There may also need to be controls for the level of logging. Bonus if the level of logging can be chosen in hindsight based on the presence of error conditions. That might mean storing very granular info in memory, but then filtering it for output, with the filter level adjusted for either normal operation, or a detected error.

This is getting a bit off the direct topic of adding op2ext as a submodule though.

**Comment by Brett208** [comment]
I can setup a post build event to move both the PDB file and DLL for NetFixClient into the same Outpost 2 copy as where op2ext is pushing it's DLL and PDB file.

Also, currently I am horizontally moving across my file system to paste DLLs and PDB files manually. It is easier if op2ext is just a subdirectory.

It also provides version control when bringing in op2ext changes.

I think it would be good to start by consolidating NetFix logging with op2ext. After that, we can explore what more is needed to get things working.

**Comment by DanRStevens** [comment]
Maybe we can setup the copy to use an environment variable. I've been thinking we should do that for a while now.

Change:
```
xcopy /y /d "$(TargetPath)" ".\Outpost2\"
```
To:
```
xcopy /y /d "$(TargetPath)" "$(Outpost2Path)"
```

Then define `Outpost2Path` for your system as one of your environment variables.

Taking it a step further, the copy can be done conditionally, only if the environment variable is defined. You can find some details here:
https://www.robvanderwoude.com/battech_defined.php

That should give something like:
```
if defined Outpost2Path (xcopy /y /d "$(TargetPath)" "$(Outpost2Path)")
```

Alternatively, you can assume a subfolder of ".\Outpost2\" if the environment variable is not defined:
```
if defined Outpost2Path (
  xcopy /y /d "$(TargetPath)" "$(Outpost2Path)"
) else (
  xcopy /y /d "$(TargetPath)" ".\Outpost2\"
)
```

At least, that could help if you want to use a common copy of Outpost 2 for testing various projects, which may be unrelated to each other.

The same variable can also be used to set the debug executable, so you can easily launch Outpost 2 with a common setting.

**Comment by Brett208** [comment]
I think I like this idea. If someone hasn't defined the environment variable, no post build copy will occur, which is nice because creating a new folder and moving content is sort of undesirable when unexpected by someone first testing the code. 

If it is a Windows environment variable, I think you would want $(Outpost2Path) to read %Outpost2Path%.

The downside is it adds a bit more complexity to understanding the post build process. I'll give it a try and see if it runs smoothly. I'm still getting used to environment variables.

-Brett

**Comment by DanRStevens** [comment]
It seems VS uses the `$(VAR)` syntax, even for environment variables. As it's not a batch file, it's free to have its own syntax. Only the variable name itself is really a global setting. The way variables are referenced is context specific.

My curiosity required I look this up to be sure. Reference:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2017
