### ISSUE TITLE
Signed/Unsigned comparison warnings

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/NetFixClient#66]
When compiling with Mingw, the following warnings appear:
```
OPUNetTransportLayer.cpp: In member function ‘virtual int OPUNetTransportLayer::Receive(OP2Internal::Packet&)’:
OPUNetTransportLayer.cpp:652:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (numBytes == -1)
       ~~~~~~~~~^~~~~
OPUNetTransportLayer.cpp:657:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if (numBytes == -1) {
        ~~~~~~~~~^~~~~
OPUNetTransportLayer.cpp: In member function ‘int OPUNetTransportLayer::ReadSocket(SOCKET, OP2Internal::Packet&, sockaddr_in&)’:
OPUNetTransportLayer.cpp:963:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (numBytes == SOCKET_ERROR) {
               ^
```

**Comment by Brett208** [comment]
Mingw is exposing some legitimate bugs with these warnings. numBytes cannot report error condition since it is unsigned in the first two. I noticed a couple other mistakes while investigating that may make a difference in how the code runs. 

I think fixing this should be a fairly high priority as this code is called every time NetFixClient is ran and is unable to report errors due to the sign mismatch.

I'll push my proposed fix tomorrow and request review on it. May want to test in a live session before pushing.

-Brett

**Comment by DanRStevens** [comment]
I think the code might actually still run correctly, due to the way signed values are promoted to unsigned values. The existing code is definitely bad form though. It's a bit annoying though how different lines of code made different assumptions about signed versus unsigned, so fixes are likely to trigger a few additional warnings, which then need to be resolved too.
