### ISSUE TITLE
Unify unsigned short definition in codebase

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#91]
A lot of the winock functions seem to take u_short. Our codebase seems split between unsigned short and USHORT.

I was thinking we could standardize to just use unsigned short within NetFixClient.

Since this is WIN32 programming, there might be an argument to use USHORT as well to try and match the coding style. However, I think we will end up moving some of this code over to a library shared between the Client and Server and it might be nice to just unify to unsigned short across the board.

#90 fixes an instance where we use unsigned short in the definition and USHORT in the declaration of a function. MSVC will compile, but it complains about this mismatch when I'm working in the codebase with Visual Studio.

**Comment by DanRStevens** [comment]
You make some good points. Using `USHORT` is kind of a Windows thing. Since we'll want to share some code between client and server, and the server runs on Linux, we may want to use an alternate type name. Also, I don't think the network code uses that actual type name. I think I chose it just because it was convenient and familiar.

I noticed the Windows and Linux libraries use different type names for that field:
[Microsoft: `sockaddr`](https://docs.microsoft.com/en-us/windows/win32/winsock/sockaddr-2)
[Linux IPv4 protocol implementation](http://man7.org/linux/man-pages/man7/ip.7.html)

It seems Windows uses `u_short`, while Linux uses `in_port_t`.

Curiously, the Linux comment reads:
`/* port in network byte order */`
Now although that would be true on both systems, I wonder if the network byte order part is enforced by the port specific data type used on Linux, rather than a generic `u_short` data type, which might represent other values in other byte orders on Windows.

----

I think I might recommend we create a type alias for this field. That way we could more easily change the type definition when compiling for different platforms.

```cpp
// Windows
using Port = u_short;
```
```cpp
// Linux
using Port = in_port_t;
```

**Comment by Brett208** [comment]
I haven't closely researched, but I am good with this suggestion. For now, I may define it in OPUNetTransportLayer to close the issue.

In the long term, do you want a library header that handles the Linux/Windows necessary includes like Winsock? Maybe it would belong there in the end.

**Comment by DanRStevens** [comment]
I haven't thought that far ahead. I suppose if it makes sense when implementing things.

Another thought is C++20 has had some work put in for a platform independent networking library, which has been published as a Technical Specification (TS):
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4734.pdf

No idea on how long before that becomes mainstream though.
