### ISSUE TITLE
Possible arithmetic overflow in OPUNetGameSelectWnd::DlgProc

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#97]
Warning	C26454	Arithmetic overflow: '-' operation produces a negative unsigned result at compile time (io.5).	NetFixClient	\NETFIXCLIENT\CLIENT\OPUNETGAMESELECTWND.CPP	111

```C++
UINT notifyCode;
...
if ((controlId == IDC_GamesList) && (notifyCode == NM_DBLCLK))
{
    ...
}
```

Below is the definition for NM_DBLCLK
```C++
#define NM_FIRST                (0U-  0U)       // generic to all controls
#define NM_DBLCLK               (NM_FIRST-3)
```

I think this means that NM_DBLCLK is a negative value. Since notifycode is an unsigned int, we are comparing an unsigned value with a negative value (hence the warning).

Is there any reason notifycode neads to be unsigned. Maybe we can just flip it to signed?

**Comment by DanRStevens** [comment]
This is yet another example of why macros are evil. They are untyped.

The valid values are effectively unsigned. However, they setup some sentinel values at the end of the valid range, and they did so using overflow. Ideally that overflow should have happened once at compile time when the constant was defined by the header, but instead it's an untyped macro that is pasted into your code, and the compiler detects the overflow there.

I suppose you could cast the value to the intended type.

Not much else  you can do that's clean, since you're forced to use the macro names here.

**Comment by Brett208** [comment]
Previous solution ended up not working

I think the warning is still emitted because the arithmetic overflow occurs before the static cast takes effect due to the MACRO expansion.

<img width="616" alt="ArithmeticOverflow" src="https://user-images.githubusercontent.com/15183337/77837869-2d49a900-713c-11ea-9302-16cee3c3b477.png">

We could do the following:
```C++ 
//Redefine NM_DBLCLK to prevent C26454 Arithmetic overflow warnings on MSVC
constexpr UINT NM_DoubleClick = static_cast<UINT>(static_cast<int>(NM_FIRST) - 3);
```

Maybe we should just add an ignore for the warning around the code block and move on though.

**Comment by DanRStevens** [comment]
I think you're right. The overflow is happening within the macro, which is defined in the Windows headers rather than our own code.

I would be fine with silencing a warning for something like this. A bit irritating, but kind of out of our control, especially if we want to stick to the definitions as Windows has defined them.
